# Generated by Django 3.0.5 on 2020-04-21 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='描述',
            new_name='description',
        ),
    ]
